# File are generated by test/aut/gen-authors.sh.
# This file lists all contributors to the repository.
# See test/aut/gen-authors.sh to make modifications.

Ola Olajide <tonnamiacart@gmail.com>
Jeffery Emuodafevware <jeffemuodafe124@gmail.com>
